GProject.WebApplication/GProject.WebApplication/Controllers/EvaluateController.cs
using GProject.Api.MyServices.IServices;
using GProject.Api.MyServices.Services;
using GProject.Data.DomainClass;
using GProject.WebApplication.Helpers;
using GProject.WebApplication.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata;
using static IdentityServer4.Models.IdentityResources;

namespace GProject.WebApplication.Controllers
{
    [GProject.WebApplication.Services.Authorize]
    public class EvaluateController : Controller
    {
        private IEvaluateService iEvaluateService;
        public EvaluateController()
        {
            iEvaluateService = new EvaluateService();
        }

        public async Task<ActionResult> Index(string sName, string sProdName, string fromDate, string toDate, int pg = 1)
        {
            try
            {
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("myRole")) && HttpContext.Session.GetString("myRole").NullToString() == "customer")
                    return RedirectToAction("AccessDenied", "Account");
                ////-- Lấy danh sách từ api
                var lstCustomer = await Commons.GetAll<Customer>(String.Concat(Commons.mylocalhost, "Customer/get-all-Customer"));
                var lstProducts = await Commons.GetAll<Product>(String.Concat(Commons.mylocalhost, "ProductMGR/get-all-Product-mgr"));
                var lstObjs = await Commons.GetAll<Evaluate>(String.Concat(Commons.mylocalhost, "Evaluate/get-all-Evaluate"));

                var data = lstCustomer
                            .Join(lstObjs, c => c.Id, e => e.CustomerId, (c, e) => new { Customer = c, Evaluate = e })
                            .Join(lstProducts, ce => ce.Evaluate.ProductId, p => p.Id, (ce, p) => new { Evaluate = ce.Evaluate, Customer = ce.Customer, Product = p })
                            .Select(x => new { Evaluate = x.Evaluate, Customer = x.Customer, Product = x.Product })
                            .OrderByDescending(c => c.Evaluate.CreateDate).ToList();
                ////-- truyền vào message nếu có thông báo
                if (!string.IsNullOrEmpty(HttpContext.Session.GetString("mess")))
                    ViewData["Mess"] = HttpContext.Session.GetString("mess");
                HttpContext.Session.Remove("mess");

                List<EvaluateViewModel> lstData = Commons.ConverObject<List<EvaluateViewModel>>(data);
                if (!string.IsNullOrEmpty(sName))
                    lstData = lstData.Where(c => c.Customer.Name.ToLower().Contains(sName.ToLower())).ToList();
                if (!string.IsNullOrEmpty(sProdName))
                    lstData = lstData.Where(c => c.Product.Name.ToLower().Contains(sProdName.ToLower())).ToList();
                if (!string.IsNullOrEmpty(fromDate))
                    lstData = lstData.Where(c => c.Evaluate.CreateDate.Date >= DateTime.Parse(fromDate).Date).ToList();
                if (!string.IsNullOrEmpty(toDate))
                    lstData = lstData.Where(c => c.Evaluate.CreateDate.Date <= DateTime.Parse(toDate).Date).ToList();

                const int pageSize = 10;
                if (pg < 1)
                    pg = 1;
                var pager = new Pager(lstData.Count(), pg, pageSize);
                this.ViewBag.Pager = pager;
                this.ViewData[nameof(sName)] = (object)sName;
                this.ViewData[nameof(sProdName)] = (object)sProdName;
                this.ViewData[nameof(fromDate)] = (object)fromDate;
                this.ViewData[nameof(toDate)] = (object)toDate;
                return View(lstData.Skip((pg - 1) * pageSize).Take(pageSize).ToList());
            }
            catch (Exception)
            {

                return RedirectToAction("AccessDenied", "Account");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Save(string Id, string ProductId, string Comment, int Rating)
        {
            try
            {
                var customer = HttpContext.Session.GetObjectFromJson<Customer>("userLogin");
                if (customer == null) return RedirectToAction("Login", "Account");

                Guid id = string.IsNullOrEmpty(Id) ? Guid.NewGuid() : new Guid(Id);
                string url = Commons.mylocalhost;
                //-- Parse lại dữ liệu từ ViewModel
                var prd = new Evaluate() { Id = id, ProductId = new Guid(ProductId), CustomerId = customer.Id, Comment = Comment, Rating = Rating, CreateDate = DateTime.Now, UpdateDate = DateTime.Now };

                //-- Check hành động là Create hay update
                if (Id == null) url += "Evaluate/add-Evaluate";
                else url += "Evaluate/update-Evaluate";

                //-- Gửi request cho api sử lí
                bool result = await Commons.Add_or_UpdateAsync(prd, url);
                return RedirectToAction("ProductDetail", "Product", new { product_id = new Guid(ProductId) });
            }
            catch (Exception)
            {
                return RedirectToAction("AccessDenied", "Account");
            }

        }


        public async Task<ActionResult> Delete(Guid? id)
        {
            try
            {
                var removeData = iEvaluateService.GetAll().FirstOrDefault(c => c.Id == id);
                if (!iEvaluateService.Delete(removeData))
                    HttpContext.Session.SetString("mess", "Failed");
                else
                    HttpContext.Session.SetString("mess", "Success");
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("AccessDenied", "Account");
            }

        }
    }
}

GProject.WebApplication/GProject.WebApplication/Views/Evaluate/Index.cshtml
@model List<GProject.WebApplication.Models.EvaluateViewModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using GProject.WebApplication.Models
@using GProject.Api.MyServices.Services;
@{
    ViewBag.Title = "Quản lý bình luận, đánh giá";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

    Pager pager = new Pager();
    int pageNo = 0;

    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }

}
<style>
    label {
        color: black;
    }

    h1 {
        color: black;
    }

    .sticky-header th {
        position: sticky;
        top: 0px;
        z-index: 1;
        background-color: #E5E5E5;
    }

    .sticky-table {
        border-collapse: separate !important;
    }
</style>

<div class="row">
    @if (@ViewData["Mess"] != null)
    {
        <p style="visibility: hidden;" id="error">@ViewData["Mess"]</p>
    }
    <form id="Searchform" name="searchForm" method="post" class="form-horizontal" action="/Evaluate/Index">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-3">
                                <div class="form-group">
                                    <label style="margin-bottom: 0;">Tên Khách hàng</label>
                                    <div class="col-12">
                                        <input type="text" id="sName" name="sName" value="@ViewData["sName"]"
                                            class="form-control" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-3">
                                <div class="form-group">
                                    <label style="margin-bottom: 0;">Tên sản phẩm</label>
                                    <div class="col-12">
                                        <input type="text" id="sProdName" name="sProdName"
                                            value="@ViewData["sProdName"]" class="form-control" />
                                    </div>
                                </div>
                            </div>

                            <div class="col-4">
                                <div class="row">
                                    <div class="form-group col-6">
                                        <label style="margin-bottom: 0;">Từ ngày</label>
                                        <input type="date" id="fromDate" name="fromDate"
                                                value="@ViewData["fromDate"]" class="form-control" />
                                    </div>
                                    <div class="form-group col-6">
                                        <label style="margin-bottom: 0;">đến ngày</label>
                                        <input type="date" id="toDate" name="toDate" value="@ViewData["toDate"]"
                                                class="form-control" />
                                    </div>
                                </div>
                            </div>

                            <div class="col-2">
                                <div class="row">
                                    <div class="col-3">
                                        <label></label>
                                        <button class="btn btn-success" onclick="$('.searchText').removeAttr('disabled')"
                                            type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                    <div class="col-3">
                                        <label></label>
                                        <a class="btn btn-outline-info" asp-action="Index">
                                            <i class="fas fa-undo-alt"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <hr style="color:red;" />
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"
                    style=" text-align:center; height:50px; padding:10px 10px 10px 10px;">
                    Danh sách bình luận đánh giá sản phẩm
                </h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive" style="overflow-y: auto; max-height: 700px;">
                    <table class="table table-bordered table-hover sticky-table">
                        <thead class="sticky-header">
                            <tr>
                                <th style="width:20px;">STT</th>
                                <th style="width:250px;">Tên khách hàng</th>
                                <th style="width:250px;">Tên sản phẩm</th>
                                <th style="width:150px;">Ngày</th>
                                <th>Bình luận</th>
                                <th style="width:100px;">Đánh giá</th>
                                <th style="width:50px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count() > 0)
                            {
                                int index = 0;
                                @foreach (var item in Model)
                                {
                                    index++;
                                    <tr>
                                        <td class="text-center">
                                            @index
                                        </td>
                                        <td>
                                            @item.Customer.Name
                                        </td>
                                        <td>
                                            @item.Product.Name
                                        </td>
                                        <td>
                                            @item.Evaluate.CreateDate.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @item.Evaluate.Comment
                                        </td>
                                        <td>
                                            @(item.Evaluate.Rating + " sao")
                                        </td>
                                        <td>
                                            <button class="btn btn-danger"
                                                onclick="location.href='@Url.Action("Delete", "Evaluate",new { id = item.Evaluate.Id})'" />
                                            <i class="fa fa-trash"></i>
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="form-footer">
                <div style="float: right">
                    @if (pager.TotalPages > 0)
                    {
                        <ul class="pagination justify-content-end">
                            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                            {
                                <li class="page-item @(pge == pager.CurrentPage ? "Active" : "")">
                                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                                        asp-route-pg="@pge">@pge</a>
                                </li>
                            }

                            @if (pager.CurrentPage < pager.TotalPages)
                            {
                                <li class="page-item">
                                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                                        asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                                </li>
                                <li class="page-item">
                                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                                        asp-route-pg="@(pager.TotalPages)">Last</a>
                                </li>
                            }
                        </ul>
                    }        
                </div>
            </div>
        </div>
    </div>
</div>

@* @if (pager.TotalPages > 0)
        {
            <ul class="pagination justify-content-end">
                <li class="page-item">
                    <a class="page-link" asp-controller="Evaluate" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                        asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                </li>

                @for (int pge = pager.StartPage; pge < pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Evaluate" asp-action="Index" asp-route-pg="@pge"> @pge</a>
                    </li>
                }

                <li class="page-item">
                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                        asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link" asp-controller="Evaluate" asp-action="Index"
                        asp-route-pg="@(pager.TotalPages)">Last</a>
                </li>
            </ul>
        } *@

<script type="text/javascript">
    $(document).ready(function () {
        var er = document.getElementById('error')
        if (er != null) {
            if ($('#error').text() == 'Failed')
                swal("Không thành công", "Xóa bình luận không thành công", "error");
            else
                swal("Thành công", "Bạn đã xóa bình luận này", "success");
        }

        $('.datefield').datepicker({
            format: 'dd/mm/yyyy'
        });
    });

</script>